### ISSUE TITLE
Every compat causes anti-footgun crash by misbehaving

### ISSUE THREAD

**Issue by ApexPredatorTV** [sisby-folk/tinkerers-smithing#42]
Hello!
I have discovered the issue, that whenever I want to use your mod in its up-to-date state, it crashes the game on startup. While 2.6.5 works, I want to develop a modpack and I really need to make use of that config file that comes with 2.6.7. I have included the log for you, which also shows the other 166 mods I use.
[latest.log](https://github.com/user-attachments/files/16073240/latest.log)

**Comment by ApexPredatorTV** [comment]
Here a new gist containing a new latest.log with crash report
https://gist.github.com/ApexPredatorTV/521058aafc1df849b12746168ec5f9fa

**Comment by sisby-folk** [comment]
I don't see any crash in this log - are you sure you sent the right one? https://mclo.gs/

**Comment by ApexPredatorTV** [comment]
[crash-2024-07-05_15.10.54-client.txt](https://github.com/user-attachments/files/16110118/crash-2024-07-05_15.10.54-client.txt)
https://mclo.gs/5W7M94H
I think that is what you were looking for.

**Comment by Onewingseraphim** [comment]
I'm glad I checked here, I'm having the same exact issue my game won't boot up on any version higher than 2.6.5, which is funny because a few days ago I could just fine so it's a newer mod I added causing a conflict I suppose but not sure which one it is. If you have a modlist maybe we could compare your list to my more recently downloaded mods and see if there's one we have in common causing the issue? (I have 533 mods installed so might take a bit of time to figure out) 😅

The weird thing is my logs aren't even showing me why the game is crashing on higher versions for some reason

with 2.6.5 my console is getting this spam quite a lot and I can't join a saved world or create a new one, removing the mod fixed the issue.

`[Render thread/ERROR] (tinkerers_smithing) [Tinkerer's Smithing] Cowardly refusing to access an unloaded tag ingredient: {"tag":"c:colorless_glass"}
java.lang.IllegalStateException: A tag ingredient was accessed before tags are loaded - This can break recipes! Report this to the mod in the trace below.
	at net.minecraft.class_1856.isFootgun(class_1856.java:3025) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.handler$lpp000$tinkerers_smithing$getMatchingStacks(class_1856.java:3033) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8105(class_1856.java) ~[client-intermediary.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.recipe.IRecipeTemplate.convertIngredients(IRecipeTemplate.java:30) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:72) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:22) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.recipe.IRecipeTemplate.createSimilar(IRecipeTemplate.java:20) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.lambda$addBlocksRecipes$9(ResourcesUtils.java:358) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.addBlocksRecipes(ResourcesUtils.java:346) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.AbstractSimpleEntrySet.generateRecipes(AbstractSimpleEntrySet.java:150) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicServerResources$7(SimpleModule.java:91) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicServerResources(SimpleModule.java:89) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.lambda$regenerateDynamicAssets$0(ServerDynamicResourcesHandler.java:38) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:80) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.regenerateDynamicAssets(ServerDynamicResourcesHandler.java:36) ~[everycomp-1.19.2-2.5.24-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:115) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:83) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:25) ~[moonlight-1.19.2-2.3.5-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
`

**Comment by sisby-folk** [comment]
> Report this to the mod in the trace below.

!

As for the other crash, you'll have to bisect

**Comment by Onewingseraphim** [comment]
Actually just got it working on version 2.5.1 for me

**Comment by sisby-folk** [comment]
closing as invalid as it's another mod misbehaving
