### ISSUE TITLE
Crashes when encountering an armor material with a null name

### ISSUE THREAD

**Issue by DrWhoCares** [sisby-folk/tinkerers-smithing#47]
Minecraft v1.20.1
Tinkerer's Smithing v2.7.0+1.20

Server fails to boot when this mod is added.

```mc_darkrpg2024  | [00:09:56] [main/INFO]: [Tinkerer's Smithing] Generating Smithing Data!
mc_darkrpg2024  | [00:09:56] [main/INFO]: [Tinkerer's Smithing] Data Initializing.
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Registered 7 Tool Materials with 169 items: [minecraft:diamond(34), minecraft:string(3), minecraft:gold(33), minecraft:stone(14), minecraft:wood(14), minecraft:iron(35), minecraft:netherite(36)]
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Registered 7 Armor Materials with 35 items: [minecraft:diamond(5), minecraft:chain(4), minecraft:gold(5), minecraft:leather(11), minecraft:turtle(1), minecraft:iron(5), minecraft:netherite(4)].
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Registered 15 Equipment Types with 1196 items: [minecraft:horse_armor(4), minecraft:hoe(35), minecraft:shield(9), minecraft:fishing_rod(1), minecraft:shovel(33), minecraft:helmet(220), minecraft:sword(210), minecraft:bow(1), minecraft:shears(1), minecraft:axe(37), minecraft:leggings(197), minecraft:pickaxe(37), minecraft:crossbow(1), minecraft:boots(200), minecraft:chestplate(210)]
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Applied 798 Unit Costs to 797 items
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Applied 381 Upgrade Paths to 52 items
mc_darkrpg2024  | [00:09:58] [main/INFO]: [Tinkerer's Smithing] Applied 264 Sacrifice Paths to 24 items
mc_darkrpg2024  | [00:09:58] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
mc_darkrpg2024  | java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Receiver class net.mcreator.themalachitemod.item.PeridotiteArmorItem$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_7694()' of interface net.minecraft.class_1741.
mc_darkrpg2024  |       at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
mc_darkrpg2024  |       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
mc_darkrpg2024  |       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
mc_darkrpg2024  |       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
mc_darkrpg2024  |       at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
mc_darkrpg2024  | Caused by: java.lang.AbstractMethodError: Receiver class net.mcreator.themalachitemod.item.PeridotiteArmorItem$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_7694()' of interface net.minecraft.class_1741.
mc_darkrpg2024  |       at folk.sisby.tinkerers_smithing.TinkerersSmithingLoader$LoaderRun.lambda$generateItemSmithingData$19(TinkerersSmithingLoader.java:331) ~[tinkerers-smithing-2.7.0+1.20.jar:?]
mc_darkrpg2024  |       at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at folk.sisby.tinkerers_smithing.TinkerersSmithingLoader$LoaderRun.generateItemSmithingData(TinkerersSmithingLoader.java:331) ~[tinkerers-smithing-2.7.0+1.20.jar:?]
mc_darkrpg2024  |       at folk.sisby.tinkerers_smithing.TinkerersSmithingLoader.generateItemSmithingData(TinkerersSmithingLoader.java:71) ~[tinkerers-smithing-2.7.0+1.20.jar:?]
mc_darkrpg2024  |       at folk.sisby.tinkerers_smithing.TinkerersSmithing.generateSmithingData(TinkerersSmithing.java:51) ~[tinkerers-smithing-2.7.0+1.20.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_1863.localvar$gmk000$tinkerers_smithing$AddRuntimeRecipes(class_1863.java:7531) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_1863.method_20705(class_1863.java:64) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
mc_darkrpg2024  |       at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
mc_darkrpg2024  |       ... 5 more```

**Comment by sisby-folk** [comment]
That random mccreator mod really *should* be returning an armor material name, but we'll add a safeguard for null names.
